### ISSUE TITLE
Unknown flag --registry-certificate jfrog.local.com

### ISSUE THREAD

**Issue by nishit93-hub** [vfarcic/kaniko-demo#1]
@vfarcic Hi,  I want to pass a certificate for a registry using kaniko. But it gives an error

```
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [/kaniko/executor]
      args:
        - "--context=dir:///application-dockerfile"
        - "--destination=jfrog.local.com/springboot/maven:5.0"
        - "--registry-certificate jfrog.local.com=/kaniko/.docker/certs/ca-certificates.crt"
```

The error is `Unknown flag --registry-certificate jfrog.local.com`.
